domainName: "https://www.whisperquestion.com"
uploadPath: /gen/resource/image/

server:
  port: 8080

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://mariadb_1:3306/wqproject?useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Seoul
    username: whisperquestion
    password: 1qw2#ER$

  jpa:
    hibernate:
      ddl-auto: validate
