domainName: "https://www.whisperquestion.com"
uploadPath: /gen/resource/image/

server:
  port: 8080

spring:
  config:
    activate:
      on-profile: prod
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://mariadb_1:3306/shop?useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Seoul
    username: wqproject
    password: wq1234!
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 37d762ffd7e136ef36d88779ff6b0509
            client-secret: 6JMtuxi3wOBJJehwu6MQiw94IpdXT1N7
            redirect-uri: ${domainName}/oauth2/callback/kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email
            client-name: kakao
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
      enabled: true

jwt:
  header: Authorization
  secret: a2FyaW10b2thcmltdG9rYXJpbXRva2WwaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbQ==
  token-validity-in-seconds: 86400 # ttl (초)

app:
  auth:
    token-secret: dev-token-secret-key
    token-expiration-time: 1209600000 #14일
  oauth2:
    authorized-redirect-uris: ${domainName}/oauth2/redirect

logging:
  level:
    org.hibernate.sql: debug
    org.springframework.coreLocalVariableTableParameterNameDiscoverer: error