domainName: "http://localhost:5173"
#uploadPath: C:/wqproject/resource/image/
uploadPath: /Users/danhyeon/wqproject/resource/image/

server:
  port: 8080

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://localhost:3306/wqproject?useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Seoul
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: validate
