domainName: "http://localhost:3000"

server:
  port: 8080

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://localhost:3306/halmang?useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Seoul
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create

jwt:
  issuer: halmang
  secret-access-key: test=access=keytest=access=keytest=access=keytest=access=keytest=access=keytest=access=keytest=access=keytest=access=keytest=access=keytest=access=key
  secret-refresh-key: test=refresh=keytest=refresh=keytest=refresh=keytest=refresh=keytest=refresh=keytest=refresh=keytest=refresh=keytest=refresh=keytest=refresh=keytest=refresh=key